name: ubuntu-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  ubuntu_rubygems:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ 2.3.8, 2.4.10, 2.5.8, 2.6.6, 2.7.1, jruby-9.2.11.1, truffleruby-20.2.0 ]
    env:
      TRUFFLERUBYOPT: "--experimental-options --testing-rubygems"
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
    timeout-minutes: 60
